language: php
php:
  - 7.3
  - 7.2
os: linux
dist: xenial
services:
  - mysql
mysql:
  username: root
  encoding: utf8
before_install:
  - cp lib/config.samp.php lib/config.php
  - mysql -e 'CREATE DATABASE samp;'
  - mysql -u root samp < db/initial.sql
  - mysql -u root samp < db/v3.1.sql
  - mysql -u root -e 'create user samp identified by "samp"; grant all on samp.* to samp;'
  - composer install
script: phpunit test/awards.test.php